export const API_END_POINT = {
  CREATE_USER: "/auth/register",
  LOGIN_USER: "/auth/login",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_ACCOUNT: "/auth/verify-account/",
  RESET_PASSWORD: "/auth/reset-password/",
  GET_AUCTION_LIST: "/auction",
  GET_AUCTION_DETAIL_BY_ID: "/auction/auction-detail",
  BID_APPLY: "/bid/create",
  GET_AUCTION_CATEGORY_LIST: "/auction-category",
  GET_PRESIGNED_URL: "/aws/get-presigned-url",
  CREATE_AUCTION: "/auction/create",
  MY_AUCTION_LIST: "/auction/my-auction",
  UPDATE_AUCTION: "/auction/update",
  DELETE_AUCTION: "/auction/delete",
  USER_DETAIL: "/user/detail",
  GET_MY_BID_LIST: "/bid/my-bid",
  ADMIN_AUCTION_LIST: "/admin/auctions",
  UPDATE_AUCTION_STATUS: "/admin/auction/update/status",
  ADMIN_USER_LIST: "/admin/user-list",
  GET_USER_DETAIL_BY_ID: "/user/user-detail",
  UPDATE_USER_DETAIL_BY_ID: "/user/update-user",
  DELETE_USER_BY_ID: "/user/delete-user",
  GET_BID_LIST_BY_AUCTION_ID: "/bid/by-auction",
};
